[Unit]
Requires=
After=network-online.target nss-lookup.target firewalld.service containerd.service time-set.target

[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock
